// Code generated by hertz generator.

package http

import (
	"context"
	"third-login/biz/service"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	auth "third-login/biz/model/api/http/auth"
)

// GetToken .
// @router /auth/token [GET]
func GetToken(ctx context.Context, c *app.RequestContext) {
	var err error
	var req auth.TokenRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(auth.TokenResponse)

	// 调用认证服务获取token
	result, err := service.NewAuthService().GetToken(ctx, req.GetPlatform(), req.GetAppId())
	if err != nil {
		c.String(consts.StatusInternalServerError, err.Error())
		return
	}

	resp.AccessToken = result

	c.JSON(consts.StatusOK, resp)
}
