// Code generated by hertz generator.

package http

import (
	"github.com/cloudwego/hertz/pkg/app"
	"third-login/biz/middleware"
)

func rootMw() []app.HandlerFunc {
	return []app.HandlerFunc{
		middleware.LoggerMiddleware(),
		middleware.CORSMiddleware(),
		middleware.RecoveryMiddleware(),
		middleware.RequestIDMiddleware(),
	}
}

func _authMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _gettokenMw() []app.HandlerFunc {
	// your code...
	return nil
}
